/* A */
SELECT I.INGREDIENTE, U.UNIDAD, IxP.CANTIDAD
FROM INGREDIENTES I
INNER JOIN INGREDIENTES_X_PLATO IxP ON I.IDINGREDIENTE = IxP.IDINGREDIENTE
INNER JOIN UNIDADES U ON IxP.IDUNIDAD = U.IDUNIDAD
WHERE IxP.IDPLATO = 1;

/* B */
SELECT SUM(P.IMPORTE) AS TOTAL FROM PLATOS_X_PEDIDO AS P WHERE CONVERT(NVARCHAR(20), P.FECHAHORA_INICIO, 103) = CONVERT(NVARCHAR(20), GETDATE()-1, 103)

/* C */
SELECT TOP 10 PL.DESCRIPCION, COUNT(PP.IDPLATO) AS CANT_VENTAS FROM PLATOS PL
INNER JOIN PLATOS_X_PEDIDO PP ON PP.IDPLATO = PL.IDPLATO
GROUP BY PL.DESCRIPCION
ORDER BY 2 DESC

/* D */
SELECT PL.DESCRIPCION, PL.TIEMPO, 
   (SELECT AVG(DATEDIFF(MINUTE, P.FECHAHORA_INICIO, P.FECHAHORA_FIN)*1.0) FROM PLATOS_X_PEDIDO P WHERE P.IDPLATO = PL.IDPLATO) AS TIEMPO_REAL
FROM PLATOS PL

--DATOS DESAGREGADOS PUNTO D PARA VERIFICACIÓN
SELECT PL.DESCRIPCION, DATEDIFF(MINUTE, P.FECHAHORA_INICIO, P.FECHAHORA_FIN) AS 'MINUTOS PREP' FROM PLATOS AS PL
INNER JOIN PLATOS_X_PEDIDO AS P ON P.IDPLATO = PL.IDPLATO
ORDER BY PL.DESCRIPCION ASC

/* E */
SELECT M.APELLIDO, M.NOMBRE, SUM(PP.IMPORTE)*M.COMISION AS DINERO
FROM MOZOS M INNER JOIN PEDIDOS P ON P.IDMOZO = M.IDMOZO
INNER JOIN PLATOS_X_PEDIDO PP ON PP.IDPEDIDO = P.IDPEDIDO
WHERE YEAR(PP.FECHAHORA_INICIO) = 2012 AND MONTH(PP.FECHAHORA_INICIO) = 5
GROUP BY M.APELLIDO, M.NOMBRE, M.COMISION

/*F*/
SELECT CAT.CATEGORIA, COUNT(P.IDCATEGORIA) AS CANTIDAD FROM CATEGORIAS CAT
INNER JOIN PLATOS P ON P.IDCATEGORIA = CAT.IDCATEGORIA
GROUP BY CAT.CATEGORIA

/*G*/
SELECT TOP 5 P.DESCRIPCION, P.DIFICULTAD FROM PLATOS P
ORDER BY P.DIFICULTAD ASC
