USE MASTER
--DROP DATABASE TP_SUGERIDO_7;
GO
CREATE DATABASE TP_SUGERIDO_7;
GO
USE TP_SUGERIDO_7;
CREATE TABLE INGREDIENTES(
    IDINGREDIENTE INT NOT NULL PRIMARY KEY,
    INGREDIENTE VARCHAR(50) NOT NULL
);
CREATE TABLE CATEGORIAS(
    IDCATEGORIA INT NOT NULL PRIMARY KEY,
    CATEGORIA VARCHAR(50) NOT NULL
);
CREATE TABLE PLATOS(
    IDPLATO INT NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR(50) NOT NULL,
    TIEMPO SMALLINT NOT NULL DEFAULT 30,
    DIFICULTAD DECIMAL(10, 2) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    IDCATEGORIA INT NOT NULL,
    FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIAS(IDCATEGORIA)
);
CREATE TABLE UNIDADES(
    IDUNIDAD INT NOT NULL PRIMARY KEY,
    UNIDAD VARCHAR(50) NOT NULL
);
CREATE TABLE INGREDIENTES_X_PLATO(
    IDINGREDIENTE INT NOT NULL,
    IDPLATO INT NOT NULL,
    IDUNIDAD INT NOT NULL,
    CANTIDAD DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (IDINGREDIENTE, IDPLATO),
    FOREIGN KEY (IDINGREDIENTE) REFERENCES INGREDIENTES(IDINGREDIENTE),
    FOREIGN KEY (IDPLATO) REFERENCES PLATOS(IDPLATO),
    FOREIGN KEY (IDUNIDAD) REFERENCES UNIDADES(IDUNIDAD)
);
CREATE TABLE MOZOS(
    IDMOZO INT NOT NULL PRIMARY KEY,
    APELLIDO VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    COMISION DECIMAL(10, 2) NOT NULL
);
CREATE TABLE PEDIDOS(
    IDPEDIDO INT NOT NULL PRIMARY KEY,
    MESA SMALLINT NOT NULL,   
    FORMA_PAGO CHAR NOT NULL CHECK(FORMA_PAGO = 'T' OR FORMA_PAGO = 'E'),
    IDMOZO INT NULL,
    FOREIGN KEY (IDMOZO) REFERENCES MOZOS(IDMOZO)
);
CREATE TABLE PLATOS_X_PEDIDO(
  IDPLATO_X_PEDIDO INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  IDPEDIDO INT NOT NULL,
  FECHAHORA_INICIO DATETIME NOT NULL,
  FECHAHORA_FIN DATETIME NOT NULL,
  IDPLATO INT NOT NULL,
  IMPORTE DECIMAL(10, 2) NOT NULL DEFAULT 0,
  FOREIGN KEY (IDPLATO) REFERENCES PLATOS(IDPLATO),
  FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDOS (IDPEDIDO)
);
---
CREATE TABLE CHEFS(
  IDCHEF INT NOT NULL PRIMARY KEY,
  APELLIDO VARCHAR(50) NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE DIA_CHEF(
  IDCHEF INT NOT NULL FOREIGN KEY REFERENCES CHEFS(IDCHEF),
  FECHAHORA_ENTRADA SMALLDATETIME NOT NULL,
  FECHAHORA_SALIDA SMALLDATETIME NOT NULL,
  PRIMARY KEY (IDCHEF, FECHAHORA_ENTRADA)
);

CREATE TABLE PROVEEDORES(
  IDPROVEEDOR INT NOT NULL PRIMARY KEY,
  DENOMINACION VARCHAR(50) NOT NULL,
  DIRECCION VARCHAR(50) NOT NULL,
  MAIL VARCHAR(50) NOT NULL,
  TEL VARCHAR(20) NOT NULL
);

CREATE TABLE RUBROS(
  IDRUBRO INT NOT NULL PRIMARY KEY,
  NOMBRE VARCHAR(50)
);

CREATE TABLE RUBROS_X_PROVEEDOR(
 IDRUBRO INT NOT NULL FOREIGN KEY REFERENCES RUBROS(IDRUBRO),
 IDPROVEEDOR INT NOT NULL FOREIGN KEY REFERENCES PROVEEDORES(IDPROVEEDOR)
 PRIMARY KEY (IDRUBRO, IDPROVEEDOR)
);

CREATE TABLE INGREDIENTES_X_PROVEEDOR(
  IDPROVEEDOR INT NOT NULL FOREIGN KEY REFERENCES PROVEEDORES(IDPROVEEDOR),
  IDINGREDIENTE INT NOT NULL FOREIGN KEY REFERENCES INGREDIENTES(IDINGREDIENTE),
  TIEMPO_ESPERA INT NOT NULL DEFAULT(0)
  PRIMARY KEY(IDPROVEEDOR, IDINGREDIENTE)
);

CREATE TABLE PEDIDOS_X_CHEF(
  IDPEDIDO INT NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES PEDIDOS(IDPEDIDO),
  IDCHEF INT NOT NULL FOREIGN KEY REFERENCES CHEFS(IDCHEF)
)

