-- SOLUCION.SQL

/*
1) - Por cada vecino, listar el apellido y nombre, tipo de propiedad, domicilio,
porcentaje de superficie construida (sobre el total), valor de la propiedad
y antiguedad. Sólo listar registros de propiedades de costo mayor a un millón de pesos
o que tengan menos de 5 años de antigüedad. (10 puntos)
*/

/*
2) - Listar todos los datos de los vecinos que no tengan propiedades de más de 
80m2 de superficie construida. (20 puntos)
*/

/*
3) - Listar por cada vecino el apellido y nombres, la cantidad de propiedades 
sin superficie construida y la cantidad de propiedades con superficie construida que posee.
(25 puntos)
*/

/*
4) - Listar por cada tipo de propiedad el valor promedio. Sólo listar aquellos
registros cuyo valor promedio supere los $900000.
(15 puntos)
*/

/*
5) - Por cada vecino, listar apellido y nombres y el total acumulado en concepto de propiedades. 
Si un vecino no posee propiedades deberá figurar acumulando 0. (15 puntos)
*/